# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "chef/ubuntu-13.10"
  config.vm.box_url = "https://vagrantcloud.com/chef/ubuntu-13.10/version/1/provider/virtualbox.box"

  config.vm.provision :shell, :path => "setup_both.sh"

  config.vm.define "box-a" do |box_a|
    box_a.vm.provision :shell, :path => "setup_box_a.sh"
    box_a.vm.network :private_network, ip: "10.0.100.10"
  end

  config.vm.define "box-b" do |box_b|
    box_b.vm.provision :shell, :path => "setup_box_b.sh"
    box_b.vm.network :private_network, ip: "10.0.100.20"
  end
end
